#!/usr/bin/env Rscript
script<-sub("^--file=","",grep("^--file=",commandArgs(FALSE),value=TRUE)[1])
source(file.path(dirname(dirname(script)),"R","bootstrap.R"))
root<-resolve_v3_root();load_v3_modules(root)
source(file.path(root,"tests","fixtures_v32.R"))
out<-file.path(root,"review","template_key_fixture");s<-make_unequal_fixture_v32(out)
tr<-head(s$binary_species,6)
a<-fit_spec_v3(s,"binary","M1",tr,"record_equal",NULL)
b<-fit_spec_v3(s,"binary","M2",tr,"record_equal",NULL)
stopifnot(identical(a$code,b$code),!identical(a$blueprint$columns,b$blueprint$columns))
if(!exists("binary_template_key_v32"))stop("BUG_REPRODUCED: same Stan code and different brms columns need distinct template keys")
stopifnot(binary_template_key_v32(a)!=binary_template_key_v32(b))
a2<-fit_spec_v3(s,"binary","M1",tr,"species_equal",NULL)
stopifnot(binary_template_key_v32(a)==binary_template_key_v32(a2))
write_json_atomic(list(status="PASS",old_collision_reproduced=TRUE,M1_M2_stan_code_identical=TRUE,M1_M2_columns_different=TRUE,template_keys_different=TRUE,same_formula_different_weights_reuses_template=TRUE),file.path(out,"status.json"))
cat("BINARY_TEMPLATE_KEY_PASS: model/columns distinguished despite identical generic Stan program\n")
