#!/usr/bin/env Rscript
script<-sub("^--file=","",grep("^--file=",commandArgs(FALSE),value=TRUE)[1])
source(file.path(dirname(dirname(script)),"R","bootstrap.R"))
root<-resolve_v3_root();load_v3_modules(root)
checks<-list()
check<-function(label,expr){ok<-tryCatch(isTRUE(force(expr)),error=function(e)FALSE);checks[[label]]<<-ok;cat(if(ok)"PASS" else "FAIL",label,"\n")}
x<-data.frame(Species=c("A","A","B"));wr<-build_train_weights(x,"record_equal");ws<-build_train_weights(x,"species_equal")
check("3.2 valid record-equal unbalanced species accepted",check_weight_contract(wr))
check("3.2 valid species-equal accepted",check_weight_contract(ws))
bad<-wr;bad$weight<-c(.5,1,1.5);check("3.2 wrong record weights rejected",!check_weight_contract(bad))
bad<-ws;bad$weight<-c(.5,1,1.5);check("3.2 species total alone insufficient if within-species weights unequal",!check_weight_contract(bad))
bad<-wr;bad$Weighting[1]<-"species_equal";check("3.2 mixed weighting labels rejected",!check_weight_contract(bad))
bad<-wr;bad$Weighting<-NULL;check("3.2 missing weighting rejected",!check_weight_contract(bad))
bad<-wr;bad$Species[1]<-NA;check("3.2 missing species rejected",!check_weight_contract(bad))
bad<-ws;bad$weight[1]<-Inf;check("3.2 nonfinite weights rejected",!check_weight_contract(bad))
e<-data.frame(RecordID=paste0("r",1:4),Route="joint_bb",Species=c("A","A","B","C"),Type=c("count","exact","count","interval"),ObservedPoint=c(.1,.4,.7,NA),PredictedPoint=c(.4,.6,.6,.4),
 LogPredictiveDensityRaw=c(-1,-2,-3,-4),PredictedPI_lower=0,PredictedPI_upper=1,PIWidth=1,IntervalCovered=c(TRUE,TRUE,TRUE,NA))
r<-evaluate_evidence(e,"record_equal","joint_bb");s<-evaluate_evidence(e,"species_equal","joint_bb")
check("3.3 distinct 3 logscore species / 2 point and PI species",r$LogScoreSpeciesUsed==3L&&r$PointSpeciesUsed==2L&&r$PISpeciesUsed==2L)
check("3.3 records and species both exposed",r$LogScoreRecordsUsed==4L&&r$PointRecords==3L&&r$PIRecords==3L)
check("7.3 record bias is mean(predicted-observed)",abs(r$Bias-(.3+.2-.1)/3)<1e-12)
check("7.3 species bias weights within valid point subset",abs(s$Bias-((.3+.2)/2-.1)/2)<1e-12)
check("7.3 bias positive means overprediction",r$Bias>0&&s$Bias>0)
only<-evaluate_evidence(e[4,,drop=FALSE],"species_equal","joint_bb")
check("3.3 interval-only has no fabricated point species",only$PointSpeciesUsed==0L&&only$PISpeciesUsed==0L&&is.na(only$Bias))
b<-data.frame(Route="binary",Species=c("A","B"),ObservedHigh=c(0,1),PredictedPrHigh=c(.2,.8),LogPredictiveDensityRaw=log(.8))
bm<-evaluate_evidence(b,"record_equal","binary")
check("binary species counts and quantitative NA are explicit",bm$LogScoreSpeciesUsed==2L&&bm$PointSpeciesUsed==0L&&bm$PISpeciesUsed==0L&&is.na(bm$Bias))
jsonlite::write_json(checks,file.path(root,"review","v32_metric_checks.json"),pretty=TRUE,auto_unbox=TRUE)
if(!all(unlist(checks)))stop("v3.2 metric regressions failed: ",paste(names(checks)[!unlist(checks)],collapse=", "))
cat("V32_METRICS_PASS\n")
